#!/bin/bash

tmux new-window -n LARP
tmux send-keys -t 0:LARP.1 "tmux split-window -h" Enter
tmux send-keys -t 0:LARP.1 "tmux split-window -v" Enter

sleep 0.3

tmux send-keys -t 0:LARP.1 "btop" Enter
tmux send-keys -t 0:LARP.2 "cmatrix" Enter
tmux send-keys -t 0:LARP.3 "fastfetch" Enter

tmux send-keys -t 0:LARP.3 "tmux kill-window"
