# .tmux.conf

# --gerneral--
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set -g status-keys vi 
setw -g mode-keys vi
set -g allow-passthrough on
set -s extended-keys always
set -s extended-keys-format csi-u

# --keybinds--
unbind C-b
set -g prefix `
bind ` send-prefix

bind r source-file ~/.config/tmux/tmux.conf

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 3
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 3

bind | split-window -h
bind _ split-window -v

# --status bar--
set -g status-position bottom
set -g status-left "[ #S ] "
set -g status-right ""

# --status bar themes--
set -g status-style 'fg=yellow'
setw -g window-status-format '  #W  '
setw -g window-status-current-format '   #W   '
setw -g window-status-current-style 'bg=yellow fg=black bold'

# --windows themes--
setw -g pane-border-style 'fg=yellow'
set -g pane-active-border-style 'fg=yellow'
