# .tmux.conf

# --gerneral--
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on


# --keybinds--
unbind C-b
set -g prefix `
bind ` send-prefix

bind r source-file ~/.config/tmux/tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h
bind _ split-window -v


# --status bar themes--
set -g status-style 'fg=yellow'
setw -g window-status-format '  #W#F  '
setw -g window-status-current-format '   #W#F   '
setw -g window-status-current-style 'bg=yellow fg=black bold'

# --windows themes--
setw -g pane-border-style 'fg=yellow'
set -g pane-active-border-style 'fg=yellow'

