add_newline = false
format = '''[\[$username$hostname $directory\] ](yellow)'''

[username]
style_user = "yellow"
style_root = "red"
show_always = true
format = "[$user]($style)"

[hostname]
style = "yellow"
ssh_only = false
format = "[@$hostname]($style)"

[directory]
style = "yellow"
format = "[$path]($style)"

[character]
success_symbol = "[\\$](yellow)"
error_symbol = "[\\$](red)"

